#ifndef JR_CONFIG_
#define JR_CONFIG_

#define JR_CRIT_ENTER()
#define JR_CRIT_ENTER_NO_DECL()
#define JR_CRIT_LEAVE()
#define JR_SCHED_SET_PRIORITY(p)
#define JR_SCHED_SET_PENDING()
#define JR_SCHED_CLEAR_PENDING()

#define JR_MAX_EVENT_SIZE 		16
#define JR_MAX_PENDING_EVENTS	10

#endif